### ISSUE TITLE
Issues with build script

### ISSUE THREAD

**Issue by HorizontalCar** [IoTS-P/SEmu-Fuzz#2] opened 2023-06-26 16:00 UTC
Hi, thank you for your work and for releasing your code! 

I am interested in running SEMU but I am unfortunately unable to build.

**Ubuntu Version:** 
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

Running: `./install_local.sh` -- I get the following error

```Building wheels for collected packages: unicorn
  Building wheel for unicorn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/.virtualenvs/semu/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ivpw6gu2
       cwd: /tmp/pip-req-build-ge4v9jaz/
  Complete output (4 lines):
  running bdist_wheel
  running build
  Building C extensions
  error: [Errno 2] No such file or directory: '/tmp/pip-req-build-ge4v9jaz/../../include/unicorn'
  ----------------------------------------
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
Failed to build unicorn
Installing collected packages: unicorn
    Running setup.py install for unicorn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/.virtualenvs/semu/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r3ff1jtu/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.virtualenvs/semu/include/site/python3.8/unicorn
         cwd: /tmp/pip-req-build-ge4v9jaz/
    Complete output (4 lines):
    running install
    running build
    Building C extensions
    error: [Errno 2] No such file or directory: '/tmp/pip-req-build-ge4v9jaz/../../include/unicorn'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/.virtualenvs/semu/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-ge4v9jaz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-r3ff1jtu/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/.virtualenvs/semu/include/site/python3.8/unicorn Check the logs for full command output.```

**Comment by shandianchengzi** [comment] 2023-07-05 17:08
Thank you for showing interest in our project, and I apologize for the delayed response. I have set up a new environment on Ubuntu 20.04 and have also encountered the issue you mentioned.

The specific cause of the error lies in the [AFLplusplus/unicorn_mode/build_unicorn_mode.sh#L204](https://github.com/AFLplusplus/AFLplusplus/blob/c4b1566ba35c697cda7822bd0cf30e2e3eeee0c7/unicorn_mode/build_unicorn_support.sh#L204) used in the [install_local.sh#L36](https://github.com/IoTS-P/SEmu-Fuzz/blob/d8a98030ad8f77bbc285377d242a470e7afcc8a4/install_local.sh#L36). There seems to be a permission issue while installing the Python bindings for Unicorn locally.

I was able to reproduce the problem in a test environment running **Ubuntu 20.04 with Python 3.8**. You can directly navigate to `/SEmu-fuzz/AFLplusplus/unicorn_mode/unicornafl/unicorn/bindings/python` and run the following command with elevated privileges using `sudo`:

```bash
sudo python3 -m pip install --user --force .
```
This command might not provide detailed error information. Instead, you can try using `python3 setup.py install` to view the specific error message, as mentioned in the [official Unicorn installation guide](https://github.com/unicorn-engine/unicorn/blob/master/bindings/python/README.TXT). ( Please note that `python3 setup.py install` is not compatible with Python >= 3.9 due to the use of older libraries in the Unicorn setup script. )

Here is the specific error message I encountered, indicating a permission conflict:

```bash
shan@shan:~/SEmu-Fuzz/AFLplusplus/unicorn_mode/unicornafl/unicorn/bindings/python$ python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-393055.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.8/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

## Solution

Using `sudo pip install .` with elevated privileges will successfully install the package, but it will be installed **in the default site-packages director**y for global Python 3 rather than in the virtual environment.

Alternatively, you can resolve this error by lowering the permissions of the problematic file using the following command: `sudo chown -R * [username]`.

In fact, it is not necessary to install Unicorn locally. We can install the compatible version of Unicorn while installing unicornafl directly using pip install, and building the python bindings of Unicorn is very slow.

So I fixed it in commit https://github.com/IoTS-P/SEmu-Fuzz/commit/c3715ccb71bab4df08900b10afcf7f4c576ce0fd. This approach avoids the need for the `build_unicorn_mode.sh` script. 

I hope this helps, and I wish you success in running the project on your end!

**Closed as completed** 2023-07-06 02:00 UTC
